apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-beesh-deployment
  labels:
    app: hi-beesh-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi-beesh-app
  template:
    metadata:
      labels:
        app: hi-beesh-app
    spec:
      containers:
        - name: hi-beesh-app
          image: bashayralabdullah/hi-beesh-app:v.02
          ports:
            - containerPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hi-beesh-app
spec:
  rules:
    - http:
        paths:
        - path: /hi-beesh-app/
          backend:
            serviceName: hi-beesh-app
            servicePort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hi-beesh-app
spec:
  selector:
    app: hi-beesh-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
